### ISSUE TITLE
write graphml is buggy

### ISSUE THREAD

**Issue by iamjli** [fraenkel-lab/OmicsIntegrator2#104]
Actually networkx's implementation of `nx.write_graphml` is buggy. When assigning node attributes via df-generated dictionary, as seen in line 692: 

`nx.set_node_attributes(nxgraph, annotation.reindex(list(nxgraph.nodes())).dropna(how='all').to_dict(orient='index'))`

if there are missing values in the df, will be recorded as `nan` type. The added annotations are strings, but if any of the nodes are missing an annotation, the feature on that node will be recorded as `nan`, so now that feature is of mixed type. Graphml gets confused and separates these mixed features into two separate string and float features. Except the float feature does not get specified in the graphml file, so you get an error like: 

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.6/site-packages/networkx/readwrite/graphml.py in decode_data_elements(self, graphml_keys, obj_xml)
    826             try:
--> 827                 data_name = graphml_keys[key]['name']
    828                 data_type = graphml_keys[key]['type']

KeyError: 'd17'
....
NetworkXError: Bad GraphML data: no key d17
```

The best fix would be on networkx's end by handling missing values correctly, but I'm going to make a quick fix here for now and submit an issue to them.

**Comment by zfrenchee** [comment]
@iamjli thanks for finding this. Please link the issue you open against networkx here.

**Comment by iamjli** [comment]
A similar issue has been previously reported: https://github.com/networkx/networkx/issues/3167
