### ISSUE TITLE
KeyError when running from Jupyter

### ISSUE THREAD

**Issue by robd02130** [fraenkel-lab/OmicsIntegrator2#106]
Sorry to bother you. I am trying to run the Example_Usage.ipynb from OmicsIntegrator2 using Jupyter notebook. I am using Python 3.7. I am getting a keyerror for Protein1 early on and I cannot tell the source. Is there a simple fix?
Rob.

**Comment by iamjli** [comment]
Sorry we never got to this. 

This error is probably due to mismatched headers in the interactome file which needs to follow the following specs: 

column1: `protein1`
column2: `protein2`
column3: `cost`

The file can have additional columns which will not be used.
