### ISSUE TITLE
Is there any way to run this without a dependency on pcst_fast?

### ISSUE THREAD

**Issue by sgosline** [fraenkel-lab/OmicsIntegrator2#107]
I can't seem to get `pcst_fast` installed on a windows machine, is there a way to run this package without the dependency?

**Comment by alexlenail** [comment]
When I was working on this, we could not build wheels on windows, so pcst_fast only works on unix machines. OmicsIntegrator2 only has plugins for pcst_fast as a backend, so sadly, there isn't a way to run it on DOS (as of early 2019)

**Comment by agitter** [comment]
@sgosline I have a prototype Docker image for Omics Integrator 2 that I'm using to run it on Windows.  I haven't pushed it to Docker Hub, but I can if this is still relevant for you.

**Comment by sgosline** [comment]
Interesting, I think I might have done this on my own at some point, just never pushed the changes. I'm still going to check out your docker branch, as it's a valuable use case for me.

**Comment by agitter** [comment]
The Dockerfile is in a different repo on a branch that is being shuffled around this week.  I can point to the more stable location after merging or give you the temporary location if you want it now.
