### ISSUE TITLE
Network summarization

### ISSUE THREAD

**Issue by iamjli** [fraenkel-lab/OmicsIntegrator2#52]
Provide summary statistics for single run forests, provide warnings when network structure is off (large star structures/many singleton nodes, etc). Write to file. 

Ideally also do this for randomizations, but the code structure has to be modified significantly.

**Comment by zfrenchee** [comment]
@iamjli if this is still something you'd like, it might be worth implementing at some point -- seems like a valuable addition to me. What do you think?

**Comment by iamjli** [comment]
Yup, shouldn't be too difficult. Won't be able to get to it for at least a week though.

**Comment by iamjli** [comment]
Added here

https://github.com/fraenkel-lab/OmicsIntegrator2/pull/103
