### ISSUE TITLE
NetworkXError: GraphML writer does not support <class 'list'> as data values.

### ISSUE THREAD

**Issue by iamjli** [fraenkel-lab/OmicsIntegrator2#80]
The `otherLocations` node attribute is a list of extracellular locations, but networkx cannot write lists to GraphML, apparently.

**Comment by zfrenchee** [comment]
Thanks for reporting this, @iamjli ! My mistake here.

**Comment by zfrenchee** [comment]
Solved in https://github.com/fraenkel-lab/OmicsIntegrator2/commit/767616af63aa968d0cc66b274017d648d195319c
