### ISSUE TITLE
Incorrect output filename

### ISSUE THREAD

**Issue by iamjli** [fraenkel-lab/OmicsIntegrator2#81]
Small one, but shouldn't it be `filename="graph_edgelist.txt"` per the docstring? 

https://github.com/fraenkel-lab/OmicsIntegrator2/blob/71d5c594898a12d9423c9c78238ed009a949c010/src/graph.py#L948

**Comment by zfrenchee** [comment]
Thanks for reporting this @iamjli. This function won't exist in 2.2, so I'm going to close this issue for now. Please re-open if I've made a mistake.
